## Calculating the inverse of a matrix usually requires a lot
## of calculations and therefore uses more resouces. Therefore,
## using a function to cache the inverse of a matrix can prove
## useful, as we can avoid doing carrying out the same calculations
## over and over in R, therefore working faster and making our code
## more effiecient.

## This function creates a special matrix which can cache its
## inverse

makeCacheMatrix <- function(x = matrix()) {
  m<-NULL
  ## used to initialize the inverse property of a matrix
  
  set<-function(y){
    x<<-y
    m<<-NULL
    ## sets the matrix
  }
  
  get<-function() x
  ## gets and returns the matrix
  
  setmatrix<-function(solve) m<<- solve
  ## set the inverse of the matrix
  
  getmatrix<-function() m
  ## gets and returns the inverse
  
  list(set=set, get=get,
       setmatrix=setmatrix,
       
       getmatrix=getmatrix)
}


## used to compute the inverse of the matrix generated by the
## makeCacheMatrix function

cacheSolve <- function(x=matrix(), ...) {
        
  ## Return a matrix that is the inverse of 'x'
  m<-x$getmatrix()
  
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  ## return the matrix if it is already known
  
  matrix<-x$get()
  ## gets the matrix
  
  m<-solve(matrix, ...)
  ## calculates the inverse of the matrix
  
  x$setmatrix(m)
  m
  ## sets the inverse
}